group=com.mineinabyss
version=0.29
# Workaround for dokka builds failing on CI, see https://github.com/Kotlin/dokka/issues/1405
#org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
idofrontVersion=2.0.0-dev.13
kotlin.native.ignoreDisabledTargets=true
org.gradle.configuration-cache=true
org.gradle.caching=true
