[libraries]
bitvector-jvm = "net.onedaybeard.bitvector:bitvector-jvm:0.1.4"
bitvector-js = "net.onedaybeard.bitvector:bitvector-js:0.1.4"
fastutil = "it.unimi.dsi:fastutil:8.2.2"
plugman = "com.rylinaux:PlugMan:2.2.5"
