name: Java CI with Gradle

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - Writerside
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build
